# Generated by Django 4.2.3 on 2023-07-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparcapp', '0003_telegramchannel_alter_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2500, verbose_name='Текст продажи')),
                ('photo', models.ImageField(blank=True, upload_to='new_car_photos', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Новый автомобиль',
                'verbose_name_plural': 'Новые автомобили',
                'ordering': ['description'],
            },
        ),
        migrations.AlterModelOptions(
            name='telegramchannel',
            options={'ordering': ['name'], 'verbose_name': 'Канал', 'verbose_name_plural': 'Каналы'},
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Канал'),
        ),
    ]
