# Generated by Django 4.2.3 on 2023-07-31 06:10

import carparcapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carparcapp', '0004_new_car_alter_telegramchannel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_car',
            name='photo',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=carparcapp.models.get_image_filename, verbose_name='Фотографии')),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='carparcapp.new_car')),
            ],
        ),
    ]
