# Generated by Django 4.2.3 on 2023-08-05 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carparcapp', '0006_category_car_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='undercat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='carparcapp.undercategory', verbose_name='Подкатегории'),
        ),
    ]
